### ISSUE TITLE
Bug when advancing from a child chd

### ISSUE THREAD

**Issue by i30817** [Manorhos/imageparse#6]
Got the python binding good enough to test some things. 

Noticed if i did a child chd from a sega game (i changed the header to change the name of the game in the copy i did before using chdman to compress the parent then the child).

So i did the obvious and did:
`chd = chdimage.open_with_parent('/home/i3/Downloads/b.chd', ['/home/i3/Downloads/a.chd'])`

That is opened the child. This reads the first (changed) sector no problems but when you advance enough to need the bytes from the parent it throws a exception:

```
>>> chd.track_sha1s()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
chdimage.ImageError: requires parent

```

I don't know how to pin point this, looks like maybe a chd-rs problem?

The python equivalent of the sha1 code minimized to reproduce shows that there

```
>>> import chdimage
>>> from chdimage import Event
>>> 
>>> chd = chdimage.open_with_parent('/home/i3/Downloads/b.chd', ['/home/i3/Downloads/a.chd'])
>>> 
>>> for x in range(0,chd.num_tracks()):
...     event = None
...     while event != Event.TRACKCHANGE and event != Event.ENDOFDISC:
...         sector = chd.copy_current_sector()
...         event = chd.advance_position()
...         print(chd.current_track_local_msf().to_bcd_values())
...         
... 
(0, 0, 1)
(0, 0, 2)
(0, 0, 3)
(0, 0, 4)
(0, 0, 5)
(0, 0, 6)
(0, 0, 7)
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
chdimage.ImageError: requires parent

```
        
7 iterations of advance_position() before the problem becomes visible.

**Comment by i30817** [comment]
It comes from when it tries to advance the hunk in this method:
```
    fn set_location_lba(&mut self, lba: u32) -> Result<(), ImageError> {
        self.current_lba = lba;
        // Set this to None so any upcoming errors making us return early don't
        // leave us in an inconsistent state
        let current_hunk_no = self.current_hunk_no;
        self.current_hunk_no = None;

        // TODO: Can we really assume that the first track's pregap is always
        // two seconds long?
        if lba < FIRST_TRACK_PREGAP {
            self.current_track = 0;
            return Ok(());
        }

        self.update_current_track(lba)?;

        let hunk_no = self.hunk_no_for_lba(lba)?;
        debug!("set_location_lba {} -> hunk_no {}", lba, hunk_no);
        if hunk_no != current_hunk_no.unwrap_or(u32::MAX) {
            if let Err(e) = self.read_hunk(hunk_no) {
                dbg!(hunk_no); dbg!(current_hunk_no); dbg!(lba);
                
                debug!("set_location_lba: {:?}", e);
                return Err(ChdImageError::from(e).into());
            }
        }
        self.current_hunk_no = Some(hunk_no);
        Ok(())
    }
```
I added the debug macro. It errors when the current hunk number changes, at lba 158

**Comment by i30817** [comment]
btw your own example to print the sha1 with a parent fails (i had some bugs in the example code above). I'm unsure if it's because of the data or not.

The game i tried this on is shining force cd and if you want i can provide the delta chd since it's only 10kb for the name change, but it's useless without the original.

**Comment by Manorhos** [comment]
Ah, you get a "requires parent" error, because the `open_with_parent()` function is broken in such a way that it doesn't open the CHD with a parent if the first hunk is contained in the child CHD, because at first I thought any call to `read_hunk_in()` would fail if the parent is not provided, not only reading the hunks that are contained in the parents.

I'm gonna rewrite that when switching to chd-rs 0.2.0.

For a child CHD where the parent contains the first hunk (I made a "Tomb Raider (USA) (Rev 1)" CHD with a "Tomb Raider (USA)" parent), I'm getting a `ChdError::DecompressionError` though, not really sure what's up with that...
Before that, I had a Silent Hill CHD referencing a parent from another region and that worked properly, but maybe it was a bogus test.

**Comment by i30817** [comment]
Good to know you've found the bug. Also bad to know there is another.

Python binding to the 'chd' part of your project, although, the exceptions handling is terrible.

<details>
  <summary>The code and a rant</summary>
  
Consolidated into 4 python exceptions with a lot of messing around. One for 'everything else' one for 'this is hard-drive' another for 'this is a gdrom', another for 'missing parent'. There is little point in separating the rest of them imo, since a program can't do anything about them.

```
use pyo3::basic::CompareOp;
use pyo3::exceptions::PyException;
use pyo3::prelude::*;
use pyo3::{create_exception, wrap_pyfunction};

use imageparse::chd::ChdImageError;
use imageparse::{Image, MsfIndexError};

//library base exception, for python to be able to 'catch the rest' or 'catch everything'
create_exception!(chdimage, ImageError, PyException);
create_exception!(chdimage, HdChdError, ImageError);
create_exception!(chdimage, GdiChdError, ImageError);
create_exception!(chdimage, OrphanError, ImageError);

#[rustfmt::skip]
fn from_chdlibrary(err: ChdImageError) -> PyErr {
    match err {
        ChdImageError::ChdError(e)                => ImageError::new_err(format!("{}", e)),
        ChdImageError::IoError(e)                 => ImageError::new_err(format!("{}", e)),
        ChdImageError::TrackParseError(e)         => ImageError::new_err(format!("{}", e)),
        ChdImageError::WrongHunkSize              => HdChdError::new_err("Hard disc chd are not supported"),
        ChdImageError::WrongBufferSize            => unreachable!(), //the buffer is created with the chd struct, not passed from user
        ChdImageError::UnsupportedSectorFormat(e) => ImageError::new_err(e),
        ChdImageError::HunkRecvError(_)           => unreachable!(), //multithreading is turned off in the features
        ChdImageError::NoTracks                   => GdiChdError::new_err("Gdi chd are not supported"),
        ChdImageError::RecursionDepthExceeded     => ImageError::new_err("Chd parent recursion depth exceeded"),
        ChdImageError::UnsupportedChdVersion      => ImageError::new_err("Chd parent is only supported for chd V3, V4 and V5"),
        ChdImageError::ParentNotFound             => OrphanError::new_err("Chd parent was not in the path arguments"),
    }
}
#[rustfmt::skip]
fn from_imagelibrary(err: imageparse::ImageError) -> PyErr {
    match err {
        imageparse::ImageError::UnsupportedFormat => ImageError::new_err("Unsupported image format"),
        imageparse::ImageError::CueError(e)       => ImageError::new_err(format!("{}", e)),
        imageparse::ImageError::ChdError(e)       => ImageError::new_err(format!("{}", e)),
        imageparse::ImageError::MsfIndexError(e)  => ImageError::new_err(format!("{}", e)),
        imageparse::ImageError::IoError(e)        => ImageError::new_err(format!("{}", e)),
        imageparse::ImageError::OutOfRange        => ImageError::new_err("Out of Range"),
    }
}
#[rustfmt::skip]
fn from_msflibrary(err: MsfIndexError) -> PyErr {
    match err {
        MsfIndexError::ParseIntError(e) => ImageError::new_err(e),
        MsfIndexError::OutOfRangeError  => ImageError::new_err("Out of Range MSF"),
        MsfIndexError::InvalidMsfError  => ImageError::new_err("Invalid MSF"),
    }
}

#[pyclass]
struct ChdImage {
    inner: imageparse::chd::ChdImage,
    buf: [u8; 2352],
}

#[derive(PartialEq, Eq)]
#[pyclass]
struct TrackType(usize);

impl TrackType {
    fn new(track: imageparse::TrackType) -> TrackType {
        match track {
            imageparse::TrackType::Mode1 => TrackType(1),
            imageparse::TrackType::Mode2 => TrackType(2),
            imageparse::TrackType::Audio => TrackType(3),
        }
    }
}

#[allow(non_snake_case)]
#[pymethods]
impl TrackType {
    #[classattr]
    fn MODE1() -> TrackType {
        TrackType(1)
    }
    #[classattr]
    fn MODE2() -> TrackType {
        TrackType(2)
    }
    #[classattr]
    fn AUDIO() -> TrackType {
        TrackType(3)
    }
    fn __str__(&self) -> String {
        match self {
            TrackType(1) => "MODE1_RAW".to_string(),
            TrackType(2) => "MODE2_RAW".to_string(),
            TrackType(3) => "AUDIO".to_string(),
            _ => unreachable!(),
        }
    }
    fn __richcmp__(&self, other: PyRef<Event>, op: CompareOp) -> Py<PyAny> {
        let py = other.py();
        match op {
            CompareOp::Eq => (self.0 == other.0).into_py(py),
            CompareOp::Ne => (self.0 != other.0).into_py(py),
            _ => py.NotImplemented(),
        }
    }
}

#[derive(PartialEq, Eq)]
#[pyclass]
struct Event(usize);

impl Event {
    fn new(track: imageparse::Event) -> Event {
        match track {
            imageparse::Event::TrackChange => Event(1),
            imageparse::Event::EndOfDisc => Event(2),
        }
    }
}

#[allow(non_snake_case)]
#[pymethods]
impl Event {
    #[classattr]
    fn TRACKCHANGE() -> Event {
        Event(1)
    }
    #[classattr]
    fn ENDOFDISC() -> Event {
        Event(2)
    }
    fn __str__(&self) -> String {
        match self {
            Event(1) => "TrackChange".to_string(),
            Event(2) => "EndOfDisc".to_string(),
            _ => unreachable!(),
        }
    }
    fn __richcmp__(&self, other: PyRef<Event>, op: CompareOp) -> Py<PyAny> {
        let py = other.py();
        match op {
            CompareOp::Eq => (self.0 == other.0).into_py(py),
            CompareOp::Ne => (self.0 != other.0).into_py(py),
            _ => py.NotImplemented(),
        }
    }
}

#[derive(PartialEq, Eq, Clone)]
#[pyclass]
pub struct MsfIndex(imageparse::MsfIndex);

#[pymethods]
impl MsfIndex {
    #[new]
    pub fn new(m: u8, s: u8, f: u8) -> PyResult<MsfIndex> {
        Ok(MsfIndex(
            imageparse::MsfIndex::new(m, s, f).map_err(from_msflibrary)?,
        ))
    }
    #[staticmethod]
    pub fn from_bcd_values(m_bcd: u8, s_bcd: u8, f_bcd: u8) -> PyResult<MsfIndex> {
        Ok(MsfIndex(
            imageparse::MsfIndex::from_bcd_values(m_bcd, s_bcd, f_bcd).map_err(from_msflibrary)?,
        ))
    }
    #[staticmethod]
    pub fn try_from_str(s: &str) -> PyResult<MsfIndex> {
        Ok(MsfIndex(
            imageparse::MsfIndex::try_from_str(s).map_err(from_msflibrary)?,
        ))
    }
    #[staticmethod]
    pub fn from_lba(sector_no: u32) -> PyResult<MsfIndex> {
        Ok(MsfIndex(
            imageparse::MsfIndex::from_lba(sector_no).map_err(from_msflibrary)?,
        ))
    }
    pub fn to_lba(&self) -> u32 {
        self.0.to_lba()
    }
    pub fn to_bcd_values(&self) -> (u8, u8, u8) {
        self.0.to_bcd_values()
    }
    fn __str__(&self) -> String {
        let (m, s, f) = self.0.to_bcd_values();
        format!("{}:{}:{}", m, s, f)
    }
    fn __repr__(&self) -> String {
        let (m, s, f) = self.0.to_bcd_values();
        format!("MsfIndex({},{},{})", m, s, f)
    }
    fn __richcmp__(&self, other: &Self, op: CompareOp) -> bool {
        match op {
            CompareOp::Lt => self.0 < other.0,
            CompareOp::Le => self.0 <= other.0,
            CompareOp::Eq => self.0 == other.0,
            CompareOp::Ne => self.0 != other.0,
            CompareOp::Gt => self.0 > other.0,
            CompareOp::Ge => self.0 >= other.0,
        }
    }
}

#[pymethods]
impl ChdImage {
    fn num_tracks(&self) -> usize {
        self.inner.num_tracks()
    }
    fn current_subchannel_q_valid(&self) -> bool {
        self.inner.current_subchannel_q_valid()
    }
    fn current_track(&self) -> PyResult<u8> {
        self.inner.current_track().map_err(from_imagelibrary)
    }
    fn current_index(&self) -> PyResult<u8> {
        self.inner.current_index().map_err(from_imagelibrary)
    }
    fn current_track_type(&self) -> PyResult<TrackType> {
        let track = self.inner.current_track_type().map_err(from_imagelibrary)?;
        Ok(TrackType::new(track))
    }
    fn first_track_type(&self) -> TrackType {
        TrackType::new(self.inner.first_track_type())
    }
    fn track_sha1s(&mut self) -> PyResult<Vec<[u8; 20]>> {
        self.inner.track_sha1s().map_err(from_imagelibrary)
    }
    fn set_location_to_track(&mut self, track: u8) -> PyResult<()> {
        self.inner
            .set_location_to_track(track)
            .map_err(from_imagelibrary)
    }
    fn advance_position(&mut self) -> PyResult<Option<Event>> {
        let event = self.inner.advance_position().map_err(from_imagelibrary)?;
        Ok(event.map(Event::new))
    }
    /// `buf` is expected to be 2352 bytes long
    fn copy_current_sector(&mut self) -> PyResult<&[u8]> {
        self.inner
            .copy_current_sector(&mut self.buf)
            .map_err(from_imagelibrary)?;
        Ok(&self.buf)
    }
    fn current_track_local_msf(&self) -> PyResult<MsfIndex> {
        Ok(MsfIndex(
            self.inner
                .current_track_local_msf()
                .map_err(from_imagelibrary)?,
        ))
    }
    fn current_global_msf(&self) -> PyResult<MsfIndex> {
        Ok(MsfIndex(
            self.inner.current_global_msf().map_err(from_imagelibrary)?,
        ))
    }
    fn track_start(&self, track: u8) -> PyResult<MsfIndex> {
        Ok(MsfIndex(
            self.inner.track_start(track).map_err(from_imagelibrary)?,
        ))
    }
    fn set_location(&mut self, target: MsfIndex) -> PyResult<()> {
        self.inner
            .set_location(target.0)
            .map_err(from_imagelibrary)?;
        Ok(())
    }
}

#[pyfunction]
fn open_with_parent(path: String, possible_parents: Vec<String>) -> PyResult<ChdImage> {
    Ok(ChdImage {
        inner: imageparse::chd::ChdImage::open_with_parent(path, &possible_parents)
            .map_err(from_chdlibrary)?,
        buf: [0u8; 2352],
    })
}

#[pyfunction]
fn open(path: String) -> PyResult<ChdImage> {
    Ok(ChdImage {
        inner: imageparse::chd::ChdImage::open(path).map_err(from_chdlibrary)?,
        buf: [0u8; 2352],
    })
}

#[pymodule]
fn chdimage(_py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(open_with_parent, m)?)?;
    m.add_function(wrap_pyfunction!(open, m)?)?;
    m.add("ImageError", _py.get_type::<ImageError>())?;
    m.add("HdChdError", _py.get_type::<HdChdError>())?;
    m.add("GdiChdError", _py.get_type::<GdiChdError>())?;
    m.add("OrphanError", _py.get_type::<OrphanError>())?;
    m.add("MsfIndex", _py.get_type::<MsfIndex>())?;
    m.add("Event", _py.get_type::<Event>())?;
    m.add("TrackType", _py.get_type::<TrackType>())?;
    Ok(())
}
```
</details>

**Comment by Manorhos** [comment]
Okay, fix and switch to chd-rs 0.2.0 pushed. I'm still getting the `DecompressionError`s though. It happens immediately upon `Chd::open()`ing my child CHD, no matter if with or without a parent, but I don't have a proper backtrace.
As `try_read_header()` seems to work, I'm thinking it might be happening here: https://github.com/SnowflakePowered/chd-rs/blob/1e09072d60a6874fc8169addf47eecfb374c5636/chd-rs/src/chdfile.rs#L63

I won't be able to look into it further until after work though.

**Comment by i30817** [comment]
This doesn't have anything to do with your error but does the code above what you linked seem strange?

```
        if let Some(p) = parent.as_ref() {
            if !header.has_parent() {
                return Err(Error::InvalidParameter);
            }
            if p.header().sha1() != p.header().sha1() {
                return Err(Error::InvalidParent);
            }
            // should be None for V4+
            if p.header().md5() != p.header.md5() {
                return Err(Error::InvalidParent);
            }
        }
```

It's testing if the same things are different to throw errors. This seems like a bug, or is there  some weird property of rust None where None != None?

Well there is actually a difference in the second if, i just don't know if it's meaningful (header reference got by function in one side and field in the other).

**Comment by Manorhos** [comment]
Oh, good eye, I didn't catch that. Pretty sure it's supposed to compare `p.header().sha1()` with `header.parent_sha1()` and the same with MD5.

**Comment by i30817** [comment]
Opened a issue on upstream.

**Comment by i30817** [comment]
BTW, i was wondering, are tracks supposed to start at zero or not?

This comment is making me paranoid: https://github.com/Manorhos/imageparse/blob/5606b383c4d293dcc359777bee21ad9c15fd9a56/src/chd.rs#L403

And i don't quite understand how the psx 'track start' could start a the end.

**Comment by Manorhos** [comment]
In the API, tracks are supposed to correspond to the real CD tracks, so they start at 1.

About that comment: Yeeeeah, I was a bit lazy there and just threw that in there to implement the GetTD command here completely https://psx-spx.consoledev.net/cdromdrive/#cdrom-status-commands
I know it's ugly and things like this are why I haven't really released this crate yet. I'll have to create an additional method for that.

**Comment by i30817** [comment]
And that zero case is just for the ps1, why? And is it really returning the end of the disc location?

I guess what i'm wondering is 'why is it not illegal to get the location of track 0'. And besides, that, people will mostly use this with the 'num_tracks' and starting at 0, not 'num_tracks+', like in here:

https://github.com/Manorhos/imageparse/blob/5606b383c4d293dcc359777bee21ad9c15fd9a56/src/lib.rs#L53

So this can be kind of confusing to know that you need to pass +1 when using something to do with the tracks in the public api.

**Comment by Manorhos** [comment]
That's mostly a documentation issue though, IMO.
But yeah, I should really add a `disc_length()` function or something and return an error if 0 is passed to `track_start()` or `set_location_to_track()` and such.

**Comment by i30817** [comment]
Personally, coming from languages that have used index 0 for the dawn of time, i have no trouble considering it as 'track 1' for apis and only bothering to add the +1 when i want to display information to the user.

**Comment by chyyran** [comment]
> This doesn't have anything to do with your error but does the code above what you linked seem strange?
> 
> ```
>         if let Some(p) = parent.as_ref() {
>             if !header.has_parent() {
>                 return Err(Error::InvalidParameter);
>             }
>             if p.header().sha1() != p.header().sha1() {
>                 return Err(Error::InvalidParent);
>             }
>             // should be None for V4+
>             if p.header().md5() != p.header.md5() {
>                 return Err(Error::InvalidParent);
>             }
>         }
> ```
> 
> It's testing if the same things are different to throw errors. This seems like a bug, or is there some weird property of rust None where None != None?
> 
> Well there is actually a difference in the second if, i just don't know if it's meaningful (header reference got by function in one side and field in the other).

good catch, fixed in 0.2.1. Thanks!

**Comment by i30817** [comment]
Can you reproduce the extraction bug still? Could it be that one of the compression methods chdman supports is not supported / well supported in chd-rs yet?

**Comment by chyyran** [comment]
> Okay, fix and switch to chd-rs 0.2.0 pushed. I'm still getting the `DecompressionError`s though. It happens immediately upon `Chd::open()`ing my child CHD, no matter if with or without a parent, but I don't have a proper backtrace. As `try_read_header()` seems to work, I'm thinking it might be happening here: https://github.com/SnowflakePowered/chd-rs/blob/1e09072d60a6874fc8169addf47eecfb374c5636/chd-rs/src/chdfile.rs#L63
> 
> I won't be able to look into it further until after work though.


https://github.com/mamedev/mame/blob/master/src/lib/util/chd.cpp#L2252

I didn't catch this `[[fallthrough]]` when implementing the conversion to Rust. Fixed in https://github.com/SnowflakePowered/chd-rs/commit/32b46d65a64ed312fd320b832c33a852138dc205 and published as 0.2.3.

I really should set up some automated testing but the problem is it's hard to find homebrew or legally redistributable games that are large enough to really test the full implementation.

**Comment by Manorhos** [comment]
Nice, works for me now with 0.2.3!
